### PR TITLE
Implement feature: stable openable overlay

### PR DESCRIPTION
**Pull request by hohserg1**
[Alt+C] are open overlay and not need to hold buttons pressed
Also added keyboard_interact_overlay event for stable overlay

### CODE REVIEW

**Comment by ben-mkiv** [comment]
so this would keep the overlay opened until ESC is pressed?

Also how would full Keyboard work with just glasses in reallife? I would suggest the user has to hold a keyboard or at least require to upgrade the glasses with a Keyboard. (which i can add to the code if the PR gets merged ~~have to look into it later again as your IDE added a lot of unnecessary spaces which makes the diff hard to read~~

edit: the changes you made look fine to me, but i'm going to add requirement for keyboard upgrade on the glasses before making a release.

Thanks for your contribution

**Comment by ben-mkiv** [comment]
Features added in OpenGlasses 2.2-44 which is on curseForge now.

**Comment by hohserg1** [comment]
```I would suggest the user has to hold a keyboard or at least require to upgrade the glasses with a Keyboard```
Good idea, I'll work on it)

**Comment by ben-mkiv** [comment]
you don't have to, the requirement for the keyboard upgrade is already added

**Comment by hohserg1** [comment]
```requirement  is already added```
But does the keyboard itself already added?

**Comment by hohserg1** [comment]
Ok
https://github.com/StarChasers/OCGlasses/commit/795379fd898dd34cd803ea66785f7309d445cd19

**Pull request merged**
